# Generated by Django 4.2.17 on 2025-01-16 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_product_seller_product_producer_delete_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_add_product', 'Can add product'), ('can_view_product', 'Can view product')]},
        ),
    ]
